on: [workflow_dispatch]
name: Upload Website to S3

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
        
      - name: Clear src directory
        run: |
          git rm -r src/
      - name: Download and unzip file
        run: |
          wget -O static-site.zip ${{ secrets.URL }}
          unzip static-site.zip -d src/
      - name: Commit and push updates
        run: |
          git add src/
          git commit -m "Update static site"
          git push origin main
      # Sync with S3 Bucket 
      - name: Sync static website with S3
        run: |
          aws s3 sync src/ s3://mosenk97bucket --delete
      - name: Stop task definition
        run: |
          aws ecs update-service --cluster Cluster --service Service --task-definition mytaskdefinition --desired-count 0
      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash
      # Create Invalidation
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E2RGF7GNXOJGJP --paths /*
