on:
  workflow_dispatch:
    branches:
      - main

name: Push to S3 and update Cloudfront

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Clear src directory
        run: |
          rm -rf src/*

      - name: Download and unzip file
        run: |
          wget -O static-site.zip ${{ secrets.URL }}
          unzip static-site.zip -d src/

      - name: Commit and push updates
        run: |
          git add src/
          git commit -m "Update static site"
          git push origin main

      - name: Sync static website with S3
        run: |
          aws s3 sync src/ s3://slwp --delete

      - name: Stop task definition
        run: |
          aws ecs update-service --cluster Cluster --service Service --task-definition mytaskdefinition --desired-count 0

      - name: Sleep for 10 seconds
        run: sleep 10
        shell: bash

      - name: Set output variable for CloudFront distribution ID
        id: cloudfront_output
        run: echo "CLOUDFRONT_DISTRIBUTION_ID=your_distribution_id" >> $GITHUB_ENV

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E2RGF7GNXOJGJP --paths "/*"
